print("Welcome to The Band Name Generator")
city = input("What is the name of the city you grew up in? ")
drink = input("What is your favorite drink? ")
color = input("What is your favorite color? ")
print("Your band should be called..." + city + " " + color + " " + drink + "!")